NameError: name 'torch' is not defined

In [3]:
import torch

In [7]:
torch.__version__

'1.9.1'

In [8]:
x=torch.rand(5,3)
print(x)

tensor([[0.7108, 0.8244, 0.9552],
        [0.2614, 0.4241, 0.7972],
        [0.3867, 0.2727, 0.6287],
        [0.9143, 0.5084, 0.6360],
        [0.2229, 0.6483, 0.8658]])


In [11]:
import numpy as np

In [12]:
numpy.__version__

'1.18.5'

In [13]:
a=np.array(1)
b=np.array(2)
print(a+b, b-a, a/b)

3 1 0.5


In [14]:
c=torch.tensor(1)
d=torch.tensor(2)
print(c+d, d-c, c/d)

tensor(3) tensor(1) tensor(0.5000)


In [17]:
e=np.zeros((3,3))
print(e, e.shape[0], e.shape[1])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 3 3


In [19]:
f=torch.zeros((3,3))
print(f, f.shape[0], f.shape[1])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 3 3


In [20]:
type(a),type(c)

(numpy.ndarray, torch.Tensor)